#!/usr/bin/env python3
import argparse
import logging
from mtrack.version import __version__
from mtrack.timer import MTrackTimer
from mtrack.export import export


def main():
    parser = argparse.ArgumentParser(description='mtrack')
    parser.add_argument('-p', '--project', help='project name')
    parser.add_argument('-ex', '--export', help='export date')
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)
    logging.getLogger('sh.command').setLevel(logging.WARNING)

    if args.export:
        export(args.project, args.export)
    elif args.project:
        timer = MTrackTimer(args.project)
        timer.run()


if __name__ == "__main__":
    main()
